### ISSUE TITLE
[FE] 2주차 첫번째 PR 리뷰 반영

### ISSUE THREAD

**Issue by hemudi** [jindonyy/issue-tracker#23]
# Description
- https://github.com/codesquad-members-2022/issue-tracker/pull/161
  2주차 첫번째 PR 리뷰를 반영한다.

# Task
## 개선 사항
- [x] baseURL 상수명 파스칼 케이스로 변경
- [x] axios handleError - console.error() 사용해보기
- [x] AxiosType Record 타입 적용
- [x] axios data any 타입 개선
- [ ] Panel ref - React.forwardRef
- [x] DropDown - useState 의 초기값 ''
- [x] boolean 타입 state toggle 축약
- [ ] z-index theme으로 관리
- [ ] Icon Union 문제
- [ ] Icon color prop
- [ ] Label - iconType 중복 제거
- [ ] 로그인 실패 사유 유저에게 알려주기

## 답변을 달아야 하는 질문
- [ ] url-loader 
- [ ] 로컬스토리지를 사용하게 된 이유
- [ ] Label status 타입의 용도
- [ ] 쿼리스트링 용도
