### ISSUE TITLE
[FE] 2주차 두번째 PR 리뷰 반영

### ISSUE THREAD

**Issue by hemudi** [jindonyy/issue-tracker#24]
# Description
- https://github.com/codesquad-members-2022/issue-tracker/pull/202
  2주차 두번째 PR 리뷰를 반영한다.

# Task
## 개선 사항
- [ ] FilterBar 의 focusStyle TextInput 파일로 이동
- [ ] filterBarProps IssueList -> FilterBar
- [ ] #35

## 답변을 달아야 하는 질문
- [x] Dropdown/Panel click에서 mouseUp으로 이벤트를 변경한 이유
- [x] Button 컴포넌트의 prop 가독성 개선 방법
- [x] 쿠키 클라이언트, 서버의 req, res 객체 첨부
