### ISSUE TITLE
[FE] 필터 dropdown

### ISSUE THREAD

**Issue by jindonyy** [jindonyy/issue-tracker#31]
# Description
react-query, axios를 사용하여 필터의 dropdown option 들을 클릭 할 때 해당 조건에 맞는 issue list 를 fetch 해온다.

# Task
- [x] FilterBar Option
  - [x] 열린 이슈
  - [ ] 내가 작성한 이슈
  - [ ] 나에게 할당된 이슈
  - [ ] 내가 댓글을 남긴 이슈
  - [x] 닫힌 이슈
