### ISSUE TITLE
[FE] FilterBar 필터 조건 설정 기능 구현

### ISSUE THREAD

**Issue by hemudi** [jindonyy/issue-tracker#33]
# Description
FilterBar 의 현재 설정 된 필터 조건을 설정하는 기능을 구현한다.

# Task
- [x] FilterBar Option
  - [x] 열린 이슈
  - [x] 내가 작성한 이슈
  - [x] 나에게 할당된 이슈
  - [x] 내가 댓글을 남긴 이슈
  - [x] 닫힌 이슈
- [x] open / close
- [x] assignee
- [x] label
- [x] milestone
- [x] author
