### ISSUE TITLE
[FE] 3주차 첫번째 PR 리뷰 반영

### ISSUE THREAD

**Issue by jindonyy** [jindonyy/issue-tracker#38]
# Description
-https://github.com/codesquad-members-2022/issue-tracker/pull/264
  3주차 첫번째 PR 리뷰를 반영한다.

# Task
## 개선 사항
- [x] printError 함수 util로 이동
- [x] InitFilterCondition pascal case 로 수정
- [x] ISSUE_FILTERS_PROPS 변수 함수 밖으로 이동
