### ISSUE TITLE
[FE] 공통 스타일 완성

### ISSUE THREAD

**Issue by jindonyy** [jindonyy/issue-tracker#4]
# Description
reset.css, common.css 작성

# Task
- [x] Global style 생성
- [x] Theme provider 생성
- [x] 스토리북에 Global Style, Theme Provider 적용
