### ISSUE TITLE
[FE] input text 글자 수 체크 구현

### ISSUE THREAD

**Issue by jindonyy** [jindonyy/issue-tracker#9]
# Description
input text 글자 수 체크 함수 custom hook 으로 구현하기

# Task
- [x] debounce 함수 구현
- [x] input text value 상태로 업데이트 함수 구현
- [x] 상태로 글자수 체크하는 함수 구현
- [x] hooks로 따로 빼기
